spring:
  application:
    name: Wego-BE

  datasource:
    url: ${DB_URL} #jdbc:mysql://localhost:3306/Wego
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

  data:
    redis:
      host: localhost
      port: 6379

kakao:
  client-id: ${KAKAO_REST_API}
  redirect-uri: ${KAKAO_REDIRECT_URI}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

  token:
    access:
      expiration: 3600000 # 1시간
    refresh:
      expiration: 604800000 # 7일

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.web: info

server:
  port: 8080

thumbnail:
  url: ${IMAGE_URL}